export const RoleEnum = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN_PARTENAIRE: 'ADMIN_PARTENAIRE',
    ADMIN_PRODUCTION: 'ADMIN_PRODUCTION',
    ADMIN_SECOND_GESTION_PARTENAIRE: 'ADMIN_SECOND_GESTION_PARTENAIRE',
}