export const routesName = {
    createAdmin: '/createAdmin',
    createFormation: '/createFormation',
  dashboard: '/',
  dashboardGlobal: '/dashboardGlobal',
    voting: '/voting',
    jobOffer: '/job-offer',
    partners: '/partners',
    productionHouse: '/maison-de-production',
    sondages: '/sondages',
    users: '/users',
    events: '/events',
    formations: '/formations',
    moovies: '/moovies',
    campagnes: '/campagnes',
    user: '/user',
    login: '/login',
    404: '/404',
    detailFormation: '/detailFormation/:formationId',
    setDetailFormation: (formationId) => `/detailFormation/${formationId}`,
  };